# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 23:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outreacheventtype',
            name='event_category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='requirements.EventCategory'),
        ),
    ]
