# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-13 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_auto_20140920_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomination',
            name='message',
            field=models.TextField(blank=True, default=b''),
        ),
    ]
