# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_cal', '0021_calendarevent_agenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventshift',
            name='attendees',
            field=models.ManyToManyField(blank=True, default=None, related_name='event_attendee', to='mig_main.UserProfile'),
        ),
    ]
