# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitearticle',
            name='tagged_members',
            field=models.ManyToManyField(blank=True, related_name='article_tagged_members', to='mig_main.MemberProfile'),
        ),
    ]
