# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-11-14 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mig_main', '0015_memberprofile_pronouns'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pronoun',
            options={'verbose_name_plural': 'Pronouns'},
        ),
    ]
