# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joiningtextfield',
            name='section',
            field=models.CharField(choices=[(b'EL', b'Eligibility Requirements'), (b'Y', b'Why Join TBP'), (b'UG', b'Requirements to Join (Undergrads)'), (b'GR', b'Requirements to Join (Grads)')], default=b'EL', help_text=b'One of the sections defined by the CHOICES attribute:', max_length=2),
        ),
        migrations.AlterField(
            model_name='joiningtextfield',
            name='text',
            field=models.TextField(help_text=b'The text which should be displayed for the section. Supports markdown formatting.'),
        ),
    ]
