# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 23:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electees', '0008_auto_20150121_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electeeprocessvisibility',
            name='term',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mig_main.AcademicTerm'),
        ),
    ]
